### ISSUE TITLE
Finishing the GitHub migration

### ISSUE THREAD

**Issue by MattesGroeger** [pecuniabanking/pecunia-client#356]
As discussed in [the Google group](https://groups.google.com/forum/#!topic/pecunia-banking/ERb8Keqs7fI) we want to migrate the whole project to GitHub.

**_Tasks:**_
- [x] Migrate all issues
- [x] Migrate the wiki
- [x] Push all the code to GitHub
- [x] Add basic `Readme`
- [x] Update [the official website](http://www.pecuniabanking.de/) to point to GitHub
- [x] Update all references in the app to point to GitHub
- [x] Disable/update the [old Google Code](https://code.google.com/p/pecuniabanking/) project and link to the new GitHub organisation
